
import React from 'react';
import { Helmet } from 'react-helmet';
import Header from '@/components/Header.jsx';
import Footer from '@/components/Footer.jsx';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { MapPin, Calendar, Users, DollarSign, Utensils, Hotel, Plane } from 'lucide-react';

const ExampleTripPage = () => {
  const tripDetails = {
    destination: 'Japan (Tokyo, Kyoto, Osaka)',
    dates: 'April 15 - April 28, 2026',
    travelers: 2,
    budget: 5000,
  };

  const itinerary = [
    {
      day: 1,
      location: 'Tokyo',
      activities: ['Toyosu Market morning tour', 'teamLab Planets immersive art'],
      restaurant: 'Sushi Saito (Michelin 3-star)',
    },
    {
      day: 2,
      location: 'Tokyo',
      activities: ['Senso-ji Temple', 'Akihabara electronics district'],
      restaurant: 'Ichiran Ramen (Shibuya)',
    },
    {
      day: 3,
      location: 'Kyoto',
      activities: ['Fushimi Inari Shrine', 'Arashiyama Bamboo Grove'],
      restaurant: 'Kikunoi (Kaiseki dining)',
    },
    {
      day: 4,
      location: 'Osaka',
      activities: ['Osaka Castle', 'Dotonbori street food tour'],
      restaurant: 'Kani Doraku (crab specialties)',
    },
  ];

  const budgetBreakdown = [
    { category: 'Flights', amount: 1500 },
    { category: 'Hotels', amount: 1200 },
    { category: 'Activities', amount: 800 },
    { category: 'Food', amount: 1000 },
    { category: 'Transport', amount: 500 },
  ];

  const transportation = [
    { from: 'San Francisco', to: 'Tokyo', method: 'Flight', cost: 1500 },
    { from: 'Tokyo', to: 'Kyoto', method: 'Shinkansen', cost: 150 },
    { from: 'Kyoto', to: 'Osaka', method: 'Local train', cost: 30 },
  ];

  return (
    <>
      <Helmet>
        <title>Example Trip: Japan - VaykAIo</title>
        <meta name="description" content="See a sample Japan trip itinerary created with VaykAIo. Explore Tokyo, Kyoto, and Osaka with AI-generated activities, restaurants, and budget breakdown." />
      </Helmet>
      <div className="min-h-screen flex flex-col">
        <Header />
        
        <section className="py-20 bg-gradient-to-b from-primary/5 to-background">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8">
            <div className="text-center mb-12">
              <h1 className="text-4xl md:text-5xl font-bold mb-6 text-balance" style={{letterSpacing: '-0.02em'}}>
                Example trip: Japan adventure
              </h1>
              <p className="text-xl text-muted-foreground max-w-3xl mx-auto leading-relaxed">
                A sample 14-day itinerary generated by VaykAIo
              </p>
            </div>

            <div className="max-w-5xl mx-auto space-y-8">
              <Card className="shadow-lg">
                <CardHeader>
                  <CardTitle className="text-2xl">Trip overview</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div className="flex items-center gap-3">
                      <MapPin className="w-5 h-5 text-primary" />
                      <div>
                        <div className="text-sm text-muted-foreground">Destination</div>
                        <div className="font-medium">{tripDetails.destination}</div>
                      </div>
                    </div>
                    <div className="flex items-center gap-3">
                      <Calendar className="w-5 h-5 text-primary" />
                      <div>
                        <div className="text-sm text-muted-foreground">Dates</div>
                        <div className="font-medium">{tripDetails.dates}</div>
                      </div>
                    </div>
                    <div className="flex items-center gap-3">
                      <Users className="w-5 h-5 text-primary" />
                      <div>
                        <div className="text-sm text-muted-foreground">Travelers</div>
                        <div className="font-medium">{tripDetails.travelers} people</div>
                      </div>
                    </div>
                    <div className="flex items-center gap-3">
                      <DollarSign className="w-5 h-5 text-primary" />
                      <div>
                        <div className="text-sm text-muted-foreground">Total budget</div>
                        <div className="font-medium">${tripDetails.budget.toLocaleString()}</div>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>

              <div>
                <h2 className="text-2xl font-semibold mb-6">Sample itinerary</h2>
                <div className="space-y-4">
                  {itinerary.map((day, index) => (
                    <Card key={index} className="bg-muted/30">
                      <CardHeader>
                        <div className="flex items-center justify-between">
                          <CardTitle className="text-lg">Day {day.day}</CardTitle>
                          <Badge variant="outline">{day.location}</Badge>
                        </div>
                      </CardHeader>
                      <CardContent className="space-y-3">
                        <div>
                          <div className="text-sm font-medium mb-2">Activities</div>
                          <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground">
                            {day.activities.map((activity, actIndex) => (
                              <li key={actIndex}>{activity}</li>
                            ))}
                          </ul>
                        </div>
                        <div className="flex items-center gap-2">
                          <Utensils className="w-4 h-4 text-primary" />
                          <span className="text-sm font-medium">Dining:</span>
                          <span className="text-sm text-muted-foreground">{day.restaurant}</span>
                        </div>
                      </CardContent>
                    </Card>
                  ))}
                </div>
              </div>

              <div>
                <h2 className="text-2xl font-semibold mb-6">Budget breakdown</h2>
                <Card>
                  <CardContent className="pt-6">
                    <div className="space-y-4">
                      {budgetBreakdown.map((item, index) => (
                        <div key={index} className="flex items-center justify-between">
                          <span className="font-medium">{item.category}</span>
                          <span className="text-muted-foreground">${item.amount.toLocaleString()}</span>
                        </div>
                      ))}
                      <div className="border-t pt-4 flex items-center justify-between font-semibold text-lg">
                        <span>Total</span>
                        <span className="text-primary">${tripDetails.budget.toLocaleString()}</span>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </div>

              <div>
                <h2 className="text-2xl font-semibold mb-6">Transportation</h2>
                <div className="space-y-3">
                  {transportation.map((transport, index) => (
                    <Card key={index} className="bg-muted/30">
                      <CardContent className="pt-6">
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-3">
                            <Plane className="w-5 h-5 text-primary" />
                            <div>
                              <div className="font-medium">{transport.from} → {transport.to}</div>
                              <div className="text-sm text-muted-foreground">{transport.method}</div>
                            </div>
                          </div>
                          <div className="font-medium">${transport.cost.toLocaleString()}</div>
                        </div>
                      </CardContent>
                    </Card>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </section>

        <Footer />
      </div>
    </>
  );
};

export default ExampleTripPage;
